---
languagecode: "en"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
title: "Kirk Easterson"
# theme: "hugo-coder" # TODO: figure out why this lines makes the build fail
enableRobotsTXT: true
