baseURL = "http://kirkeasterson.com/"
languagecode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Kirk Easterson"
theme = "hugo-coder"

[languages]
[languages.en]
disabled = false
languageCode = "en-GB"
languageDirection = "ltr"
languageName = "🇬🇧"
weight = 1

[languages.se]
disabled = false
languageCode = "se-SV"
languageDirection = "ltr"
languageName = "🇸🇪"
weight = 2

[languages.no]
disabled = false
languageCode = "nb-NO"
languageDirection = "ltr"
languageName = "🇳🇴"
weight = 3
