author = "Kirk Easterson"
avatarURL = "img/me.png"
colorScheme = "auto"
dateFormat = "02 January 2006"
favicon_32 = "img/favicon-32x32.png"
favicon_16 = "img/favicon-16x16.png"
touchIcon = "img/apple-touch-icon.png"
hideCopyright = true
hideCredits = true
hideFooter = true
since = 2019

[[social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/KirkEasterson"

[[social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/kirkeasterson/"
