StylesPath = styles

MinAlertLevel = suggestion

Packages = RedHat, proselint, write-good, alex

Vocab = DomainTerms

[*.{md,yaml}]
BasedOnStyles = Vale, RedHat, proselint, write-good, alex

RedHat.GitLinks = no

# temporarily ignore non-english pages
[*.se.md]
BasedOnStyles =
[*.no.md]
BasedOnStyles =

# directories to ignore
[src/themes/*]
BasedOnStyles =
[styles/*]
BasedOnStyles =
