---
services:
  hugo:
    container_name: hugo
    image: hugomods/hugo:base-0.147.9
    network_mode: "host"
    volumes:
      - ./src:/src

  yamllint:
    container_name: yamllint
    image: registry.gitlab.com/pipeline-components/yamllint:latest
    volumes:
      - ./:/code

  markdownlint:
    container_name: markdownlint
    image: registry.gitlab.com/pipeline-components/markdownlint:latest
    volumes:
      - ./:/code
      - /code/src/themes/

  tflint:
    container_name: tflint
    image: ghcr.io/terraform-linters/tflint:v0.63.0
    volumes:
      - ./infrastructure/terraform/:/data
