---
services:
  hugo:
    container_name: hugo
    image: hugomods/hugo:base-0.147.9
    network_mode: "host"
    volumes:
      - ./src:/src

  tflint:
    container_name: tflint
    image: ghcr.io/terraform-linters/tflint:v0.63.0
    volumes:
      - ./infrastructure/terraform/:/data
