---
services:
  hugo:
    container_name: hugo
    image: hugomods/hugo:base-0.147.9
    network_mode: "host"
    volumes:
      - ./src:/src

  vale:
    image: docker.io/grafana/vale:4dbecae7443c69b3e5fdfeeac7037a339cb82e4c
    container_name: vale
    volumes:
      - .:/data
      - ./config:/data/styles/config
    working_dir: /data

  markdownlint:
    container_name: markdownlint
    image: registry.gitlab.com/pipeline-components/markdownlint:latest
    volumes:
      - ./:/code
      - /code/src/themes/
      - /code/styles/

  yamllint:
    container_name: yamllint
    image: registry.gitlab.com/pipeline-components/yamllint:latest
    volumes:
      - ./:/code

  tflint:
    container_name: tflint
    image: ghcr.io/terraform-linters/tflint:v0.63.0
    volumes:
      - ./infrastructure/terraform/:/data
