---
services:
  hugo:
    container_name: hugo
    image: peaceiris/hugo:v0.125.1
    ports:
      - 1313:1313
    volumes:
      - ${PWD}/src:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
