baseURL = "http://kirkeasterson.com/"
languagecode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Kirk Easterson"
theme = "hugo-coder"

[languages]
[languages.en]
contentDir = "content/en"
disabled = false
languageCode = "en-GB"
languageDirection = "ltr"
languageName = "🇬🇧"
weight = 1
[languages.se]
contentDir = "content/se"
disabled = false
languageCode = "se-SV"
languageDirection = "ltr"
languageName = "🇸🇪"
weight = 2
[languages.no]
contentDir = "content/no"
disabled = false
languageCode = "nb-NO"
languageDirection = "ltr"
languageName = "🇳🇴"
weight = 3


[params]
author = "Kirk Easterson"
avatarURL = "img/me.png"
colorScheme = "auto"
dateFormat = "02 January 2006"
favicon_32 = "img/favicon-32x32.png"
favicon_16 = "img/favicon-16x16.png"
touchIcon = "img/apple-touch-icon.png"
# footerContent = "Enter a text here."
# gravatar = "kirk.easterson@gmail.com"
hideCopyright = true
hideCredits = true
hideFooter = true
since = 2019

[languages.en.params]
description = "Kirk Easterson's personal website"
info = ["Developer", "Musician"]
keywords = "programmer,developer,personal"
since = 2019

[languages.se.params]
description = "Kirk Easterson's personliga hemsida"
info = ["Utvecklare", "Musiker"]
keywords = "programmer,developer,personal"
since = 2019

[languages.no.params]
description = "Kirk Easterson's personlige nettsted"
info = ["Utvikler", "Musiker"]
keywords = "programmer,developer,personal"
since = 2019


[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/KirkEasterson"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/kirkeasterson/"

[[languages.en.menu.main]]
name = "About Me"
weight = 1
url = "about/"

[[languages.se.menu.main]]
name = "Om mig"
weight = 1
url = "om/"

[[languages.no.menu.main]]
name = "Om meg"
weight = 1
url = "om/"


[[languages.en.menu.main]]
name = "Contact Me"
weight = 2
url = "contact/"


[[languages.se.menu.main]]
name = "Kontakta mig"
weight = 2
url = "kontakta/"


[[languages.no.menu.main]]
name = "Kontakt meg"
weight = 2
url = "kontakt/"
