---
name: build

"on": [push]

env:
  BUILD_ARTIFACT: "build"
  LIGHTHOUSE_ARTIFACT: "lighthouse"

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - run: make build

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: src/public

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
