---
name: build and deploy

on: [push]

env:
  BUILD_ARTIFACT: "build"
  LIGHTHOUSE_ARTIFACT: "lighthouse"

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: make build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: src/public

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  lighthouse:
    # if: github.ref == 'refs/heads/main'
    # needs: deploy
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install lighthouse
        run: npm install -g @lhci/cli@0.13.x

      - name: Run lighthouse
        run: make lh-ci

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LIGHTHOUSE_ARTIFACT }}
          path: ".lighthouseci"
