---
name: build and deploy

on: [push]

env:
  BUILD_ARTIFACT: "public"

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: make build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: src/public
          retention-days: 10

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: ".lighthouserc.yml"

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: "./public"

      - name: Run lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: ".lighthouserc.yml"
          temporaryPublicStorage: true

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
