---
name: build and deploy

on: [push]

env:
  BUILD_ARTIFACT: "build"

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo -s src/ --minify

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: $BUILD_ARTIFACT
          path: src/public
          retention-days: 10

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: $BUILD_ARTIFACT
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
