---
name: Deploy

on:
  push:
    branches:
      - main
  workflow_run:
      workflows: [Build]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/public
