---
name: docker

on: [push]

jobs:
  smoke-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: hoverkraft-tech/compose-action@v2.2.0
