---
name: lighthouse

on: [push]

env:
  BUILD_ARTIFACT: "lighthouse"

jobs:

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - uses: browser-actions/setup-chrome@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install lighthouse
        run: npm install -g @lhci/cli@0.13.x

      - name: Run lighthouse
        run: lhci autorun

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ".lighthouseci"
