---
name: terraform

on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run terraform-lint
        uses: actionshub/terraform-lint@2.0.1
