---
name: yml

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.yml'
  pull_request:
    paths:
      - '**.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
